export interface Option {
  system: string;
  id_main: string;
  id_sub: string;
  span: string;
  dimension_x: number;
  dimension_y: number;
  dimension_m2: number;
  weight: number;
  no_solar_panel: number;
  energy: number;
}

export const DATA_SOURCE: Option[] = [
  {
    system: 'System A one column',
    id_main: 'A1',
    id_sub: 'A1.1',
    span: '2m',
    dimension_x: 2,
    dimension_y: 3,
    dimension_m2: 6,
    weight: 134.86,
    no_solar_panel: 3,
    energy: 1083,
  },
  {
    system: 'System A one column',
    id_main: 'A1',
    id_sub: 'A1.2',
    span: '0m',
    dimension_x: 3,
    dimension_y: 4,
    dimension_m2: 12,
    weight: 237.87,
    no_solar_panel: 5,
    energy: 2165,
  },
  {
    system: 'System A one column',
    id_main: 'A1',
    id_sub: 'A1.3',
    span: '0m',
    dimension_x: 4,
    dimension_y: 4,
    dimension_m2: 16,
    weight: 276.75,
    no_solar_panel: 7,
    energy: 2887,
  },
  {
    system: 'System A one column',
    id_main: 'A1',
    id_sub: 'A1.4',
    span: '0m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 501.94,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System A one column',
    id_main: 'A1',
    id_sub: 'A1.5',
    span: '0m',
    dimension_x: 5,
    dimension_y: 6,
    dimension_m2: 30,
    weight: 620.15,
    no_solar_panel: 13,
    energy: 5413,
  },
  {
    system: 'System B two column',
    id_main: 'B1',
    id_sub: 'B1.1',
    span: '3m',
    dimension_x: 2,
    dimension_y: 4,
    dimension_m2: 8,
    weight: 180.3,
    no_solar_panel: 3,
    energy: 1443,
  },
  {
    system: 'System B two column',
    id_main: 'B1',
    id_sub: 'B1.2',
    span: '3m',
    dimension_x: 4,
    dimension_y: 4,
    dimension_m2: 16,
    weight: 313.48,
    no_solar_panel: 7,
    energy: 2887,
  },
  {
    system: 'System B two column',
    id_main: 'B1',
    id_sub: 'B1.3',
    span: '3m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 390.74,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System B two column',
    id_main: 'B2',
    id_sub: 'B2.1',
    span: '4m',
    dimension_x: 4,
    dimension_y: 4,
    dimension_m2: 16,
    weight: 333.54,
    no_solar_panel: 7,
    energy: 2887,
  },
  {
    system: 'System B two column',
    id_main: 'B2',
    id_sub: 'B2.2',
    span: '4m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 468.99,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System B two column',
    id_main: 'B2',
    id_sub: 'B2.3',
    span: '4m',
    dimension_x: 6,
    dimension_y: 6,
    dimension_m2: 36,
    weight: 633.35,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System B two column',
    id_main: 'B3',
    id_sub: 'B3.1',
    span: '5m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 445.99,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System B two column',
    id_main: 'B3',
    id_sub: 'B3.2',
    span: '5m',
    dimension_x: 6,
    dimension_y: 6,
    dimension_m2: 36,
    weight: 671.4,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System B two column',
    id_main: 'B3',
    id_sub: 'B3.3',
    span: '5m',
    dimension_x: 6,
    dimension_y: 8,
    dimension_m2: 48,
    weight: 803.47,
    no_solar_panel: 20,
    energy: 8660,
  },
  {
    system: 'System B two column',
    id_main: 'B4',
    id_sub: 'B4.1',
    span: '6m',
    dimension_x: 6,
    dimension_y: 6,
    dimension_m2: 36,
    weight: 741.92,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System B two column',
    id_main: 'B4',
    id_sub: 'B4.2',
    span: '6m',
    dimension_x: 6,
    dimension_y: 8,
    dimension_m2: 48,
    weight: 821.3,
    no_solar_panel: 20,
    energy: 8660,
  },
  {
    system: 'System B two column',
    id_main: 'B4',
    id_sub: 'B4.3',
    span: '6m',
    dimension_x: 8,
    dimension_y: 8,
    dimension_m2: 64,
    weight: 1305.41,
    no_solar_panel: 27,
    energy: 11547,
  },
  {
    system: 'System C four column',
    id_main: 'C1',
    id_sub: 'C1.1',
    span: '3m',
    dimension_x: 2,
    dimension_y: 4,
    dimension_m2: 8,
    weight: 204.71,
    no_solar_panel: 3,
    energy: 1443,
  },
  {
    system: 'System C four column',
    id_main: 'C1',
    id_sub: 'C1.2',
    span: '3m',
    dimension_x: 4,
    dimension_y: 4,
    dimension_m2: 16,
    weight: 301.0,
    no_solar_panel: 7,
    energy: 2887,
  },
  {
    system: 'System C four column',
    id_main: 'C1',
    id_sub: 'C1.3',
    span: '3m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 396.21,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System C four column',
    id_main: 'C2',
    id_sub: 'C2.1',
    span: '4m',
    dimension_x: 4,
    dimension_y: 4,
    dimension_m2: 16,
    weight: 365.73,
    no_solar_panel: 7,
    energy: 2887,
  },
  {
    system: 'System C four column',
    id_main: 'C2',
    id_sub: 'C2.2',
    span: '4m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 411.74,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System C four column',
    id_main: 'C2',
    id_sub: 'C2.3',
    span: '4m',
    dimension_x: 6,
    dimension_y: 6,
    dimension_m2: 36,
    weight: 665.8,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System C four column',
    id_main: 'C3',
    id_sub: 'C3.1',
    span: '5m',
    dimension_x: 4,
    dimension_y: 6,
    dimension_m2: 24,
    weight: 475.31,
    no_solar_panel: 10,
    energy: 4330,
  },
  {
    system: 'System C four column',
    id_main: 'C3',
    id_sub: 'C3.2',
    span: '5m',
    dimension_x: 6,
    dimension_y: 7,
    dimension_m2: 36,
    weight: 701.64,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System C four column',
    id_main: 'C3',
    id_sub: 'C3.3',
    span: '4m',
    dimension_x: 6,
    dimension_y: 8,
    dimension_m2: 48,
    weight: 875.67,
    no_solar_panel: 20,
    energy: 8660,
  },
  {
    system: 'System C four column',
    id_main: 'C4',
    id_sub: 'C4.1',
    span: '2m',
    dimension_x: 6,
    dimension_y: 6,
    dimension_m2: 36,
    weight: 816.46,
    no_solar_panel: 15,
    energy: 6495,
  },
  {
    system: 'System C four column',
    id_main: 'C4',
    id_sub: 'C4.2',
    span: '3m',
    dimension_x: 6,
    dimension_y: 8,
    dimension_m2: 48,
    weight: 948.49,
    no_solar_panel: 20,
    energy: 8660,
  },
  {
    system: 'System C four column',
    id_main: 'C4',
    id_sub: 'C4.3',
    span: '6m',
    dimension_x: 8,
    dimension_y: 8,
    dimension_m2: 64,
    weight: 1142.8,
    no_solar_panel: 27,
    energy: 11547,
  },
];
